### ISSUE TITLE
Docs link are broken

### ISSUE THREAD

**Issue by naresh-a** [OWASP/crAPI#106]
**Describe the bug**
Links in docs overview are broken

**To Reproduce**
1. Go to https://github.com/OWASP/crAPI/blob/develop/docs/overview.md
2. Try Clicking on - For deployment options, visit [the setup instructions] and 
To know more about [challenges] in crAPI, visit challenges.
3. You will see 404 error page

**Comment by nikhil-rajesh** [comment]
Fixed in #98
