### ISSUE TITLE
Build an IAM module that can centrally manage the vulnerabilities like JWT/Access Key etc

### ISSUE THREAD

**Issue by piyushroshan** [OWASP/crAPI#109]
**Is your feature request related to a problem? Please describe.**
Build an IAM module that can centrally manage the vulnerabilities like JWT/Access Key etc
There are many JWT-based vulnerabilities that need we need to target.
Algorithm confusion, signature tampering, header tampering, JWT expiry, JWKS
Similarly, target Client ID/Secret forms.

**Describe the solution you'd like**
Build an IAM module that can centrally manage the vulnerabilities and remove dependency on services.

**Describe alternatives if any you've considered**
N/A

**Additional context**
TODO

**Comment by nikhil-rajesh** [comment]
Fixed in #148 and #151
