### ISSUE TITLE
Document explaining architecture of crAPI

### ISSUE THREAD

**Issue by JBAhire** [OWASP/crAPI#114]
**Is your feature request related to a problem? Please describe.**
We need a clear and concise document that has an architecture diagram for crAPI and explain architecture and caveats. 

**Describe the solution you'd like**
Separate architecture diagram and document linked to README.

**Comment by drraghavendra** [comment]
@JBAhire Please make a note as the below https://owasp.org/crAPI/docs/docs/setup.md redirected to 404 Error

**Comment by sanket-mundra** [comment]
Can you please assign it to me?

**Comment by testingGarage** [comment]
@JBAhire please assign this ticket to me.

**Comment by testingGarage** [comment]
@JBAhire , @piyushroshan 

Please have a look at this PR -- https://github.com/OWASP/crAPI/pull/136

**Comment by nikhil-rajesh** [comment]
Merged #136
