### ISSUE TITLE
Add Kafka service in crAPI

### ISSUE THREAD

**Issue by JBAhire** [OWASP/crAPI#115]
**Is your feature request related to a problem? Please describe.**
crAPI lacks messaging services. Adding some Kafka pipelines will help in demoing Kafka vulnerabilities as well. 

**Describe the solution you'd like**
@inonshk ,@piyushroshan would like to hear your thoughts about doing this as well as solutions around it.

**Comment by piyushroshan** [comment]
That can make crAPI bloated for vulnerabilities that can be demonstrated by other services. Not in favor of kafka here.
