### ISSUE TITLE
A hacking guide which helps in finding and demoing vulnerabilities in crAPI

### ISSUE THREAD

**Issue by JBAhire** [OWASP/crAPI#116]
**Is your feature request related to a problem? Please describe.**
A guide that helps in understanding steps to reproduce a current set of vulnerabilities that exist in crAPI. 

**Describe the solution you'd like**
A document that lists down solutions to the challenges in crAPI. Something similar to what Juice shop has here: https://pwning.owasp-juice.shop/appendix/solutions.html 

**Describe alternatives if any you've considered**
NA

**Additional context**
NA

**Comment by nikhil-rajesh** [comment]
A few have been implemented in [/docs/challengeSolutions.md](/docs/challengeSolutions.md)

**Comment by nikhil-rajesh** [comment]
Duplicated issue #95
