### ISSUE TITLE
Provide troubleshooting guide for general issues while installing and running crAPI

### ISSUE THREAD

**Issue by JBAhire** [OWASP/crAPI#117]
**Is your feature request related to a problem? Please describe.**
Users sometimes face problems with getting started with docker, Kubernetes, etc. May it be resource constraints, may it be configs, may it issues specific to some database or start-up. We should have a troubleshooting guide with all the known issues and their solutions. 

**Describe the solution you'd like**
A troubleshooting document that lists down all the known issues we all have faced and also documents solutions for them. 

**Describe alternatives if any you've considered**
Refer to the juice shop troubleshooting guide: https://pwning.owasp-juice.shop/appendix/troubleshooting.html 

**Additional context**
NA

**Comment by Apollo9999** [comment]
@JBAhire Please assign to me

**Comment by Apollo9999** [comment]
Links to look out for  1) https://www.youtube.com/watch?v=ByW_yobA2aM

**Comment by sanket-mundra** [comment]
Hey @JBAhire, have a look at this PR [#138](https://github.com/OWASP/crAPI/pull/138)

**Comment by JBAhire** [comment]
Done as part of #138 ! thanks, @sanket-mundra !
