### ISSUE TITLE
Capability to demonstrate "CWE-798: Use of hard coded credentials" with crAPI

### ISSUE THREAD

**Issue by JBAhire** [OWASP/crAPI#119]
**Is your feature request related to a problem? Please describe.**
crAPI currently doesn't demonstrate CWE-798. We want to add capability in crAPI which will help in demoing CWE-798. 

**Describe the solution you'd like**
https://cwe.mitre.org/data/definitions/798.html 

**Describe alternatives if any you've considered**
NA

**Additional context**
NA

**Comment by sanket-mundra** [comment]
Can you please assign it to me?
