### ISSUE TITLE
criapi-workshop fails to build

### ISSUE THREAD

**Issue by jaemae** [OWASP/crAPI#13]
I am experiencing problems building the criapi application.  crapi-workshop image will not build.  Are there detailed instructions on how to get the application up and running.  
![image](https://user-images.githubusercontent.com/94505715/143949149-6e0e0dce-6331-4c1d-af8b-8f1515e2e2a8.png)

getting this error "/bin/sh: /app/runner.sh: not found"

**Comment by xieronnie** [comment]
getting same issue. please let us know if you resolve it.

**Comment by xieronnie** [comment]
This was actually my issue:

ImportError: Error loading shared library libffi.so.7: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so)

I was able to fix it by adding this to workshops Dockerfile

RUN ln -s /usr/lib/libffi.so.8 /usr/lib/libffi.so.7

Basically, it symlinks libffi7 to libffi8
