### ISSUE TITLE
crAPI Postman Collection Issue

### ISSUE THREAD

**Issue by rallapallinagarjun** [OWASP/crAPI#154]
The latest Postman collection is not loading on Postman, pls find a solution for that

**Comment by piyushroshan** [comment]
Looking into it. Will update soon if that's the case.

**Comment by nikhil-rajesh** [comment]
Fixed in [commit](https://github.com/OWASP/crAPI/commit/6e149d1e7cdb2ac7dac80f53bc010484cb2fdba9). Please feel free to reopen issue if issue persists.
