### ISSUE TITLE
ERROR: for crapi-web  Container "8054b214c1ec" is unhealthy.

### ISSUE THREAD

**Issue by mhmd-git** [OWASP/crAPI#161]
I'm pulling the latest docker images in Kali-Linux then running:
`docker-compose -f docker-compose.yml --compatibility up -d`
I receive the following response:
```
ERROR: for crapi-web  Container "8054b214c1ec" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Logs:
```
 sudo docker logs 8054b214c1ec
Creating test database for alias 'default'...
Creating test database for alias 'mongodb'...
root         ERROR    /workshop/api/mechanic/signup - {'name': 'MechRaju', 'email': 'mechraju@crapi.com', 'mechanic_code': 'TRAC_MEC_3', 'number': '9123456708'} - 400 -{'password': [ErrorDetail(string='This field is required.', code='required')]}
django.request WARNING  Bad Request: /workshop/api/mechanic/signup
.django.request WARNING  Bad Request: /workshop/api/mechanic/signup
.django.request WARNING  Bad Request: /workshop/api/mechanic/signup
.django.request WARNING  Unauthorized: /workshop/api/mechanic/
django.request WARNING  Unauthorized: /workshop/api/mechanic/
.django.request WARNING  Unauthorized: /workshop/api/mechanic/
..root         ERROR    /workshop/api/merchant/contact_mechanic - {'mechanic_api': 'https://www.google.com', 'number_of_repeats': 5, 'mechanic_code': 'TRAC_MEC_3', 'vin': '9NFXO86WBWA082766', 'problem_details': 'My Car is not working'} - 400 -{'repeat_request_if_failed': [ErrorDetail(string='This field is required.', code='required')]}
django.request WARNING  Bad Request: /workshop/api/merchant/contact_mechanic
.root         INFO     Repeat count: 0
root         INFO     Got a valid response at repeat count: 0
.django.request ERROR    Service Unavailable: /workshop/api/merchant/contact_mechanic
..root         INFO     Repeat count: 0
root         INFO     Repeat count: 1
root         INFO     Repeat count: 2
root         INFO     Repeat count: 3
root         INFO     Repeat count: 4
root         INFO     Repeat count: 5
django.request WARNING  Not Found: /workshop/api/merchant/contact_mechanic
.django.request WARNING  Bad Request: /workshop/api/shop/apply_coupon
ProductTest  INFO     {'message': 'TRAC100 Coupon code is already claimed by you!! Please try with another coupon code'}
.root         ERROR    /workshop/api/shop/apply_coupon - {'coupon_code': 'TRAC105', 'amount': 75} - 400 -Coupon matching query does not exist.
django.request WARNING  Bad Request: /workshop/api/shop/apply_coupon
ProductTest  INFO     {'message': 'Coupon not found'}
.django.request WARNING  Bad Request: /workshop/api/shop/apply_coupon
ProductTest  INFO     {'message': '9123456708 Coupon code is already claimed by you!! Please try with another coupon code'}
.ProductTest  INFO     {'credit': 175.0, 'message': 'Coupon successfully applied!'}
.
----------------------------------------------------------------------
Ran 15 tests in 141.909s

OK
Destroying test database for alias 'default'...
Destroying test database for alias 'mongodb'...
This version of djongo does not support "NULL, NOT NULL column validation check" fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "schema validation using CONSTRAINT" fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "schema validation using KEY" fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "schema validation using REFERENCES" fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "COLUMN DROP NOT NULL " fully. Visit https://www.patreon.com/nesdis
This version of djongo does not support "DROP CASCADE" fully. Visit https://www.patreon.com/nesdis
System check identified no issues (0 silenced).
Operations to perform:
  Apply all migrations: user
Running migrations:
  Applying user.0001_initial... FAKED
Operations to perform:
  Apply all migrations: crapi
Running migrations:
  Applying crapi.0001_initial... OK
Operations to perform:
  Apply all migrations: db
Running migrations:
  Applying db.0001_initial... OK
django.utils.autoreload INFO     Watching for file changes with StatReloader

```

**Comment by 5qu1n7** [comment]
any update on this, encountered this today as well

**Comment by mhmd-git** [comment]
No updates yet

**Comment by mathew-jose** [comment]
Can you try
`VERSION=develop docker-compose -f docker-compose.yml pull`
and then
`VERSION=develop docker-compose -f docker-compose.yml --compatibility up -d`
Locally present images might be outdated.

**Comment by 5qu1n7** [comment]
┌──(root㉿kali)-[~/API_Lab/crapi]
└─# VERSION=develop docker-compose -f docker-compose.yml pull
Pulling postgresdb      ... done
Pulling mongodb         ... done
Pulling crapi-identity  ... done
Pulling crapi-community ... done
Pulling crapi-workshop  ... done
Pulling crapi-web       ... done
Pulling mailhog         ... done
                                                                                                                                                                                            
┌──(root㉿kali)-[~/API_Lab/crapi]
└─# VERSION=develop docker-compose -f docker-compose.yml --compatibility up -d
Recreating postgresdb ... done
Recreating mailhog    ... done
Starting mongodb      ... done
Recreating crapi-identity ... done
Creating crapi-community  ... done

ERROR: for crapi-workshop  Container "a06e1aacd28e" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by mathew-jose** [comment]
Could you attach the logs of all containers, this will help us debug the issue. Also do upload the logs as a file.

**Comment by 5qu1n7** [comment]
Hopefully this helps

[crapi_logs.txt](https://github.com/OWASP/crAPI/files/10406553/crapi_logs.txt)

**Comment by nikhil-rajesh** [comment]
The error says that there is some issue connecting with the database, most probably postgres container did not come up because of old docker-comopse files.
1. Can you completely remove all crapi related container instances including postgresql and mongodb using `docker container rm` command
2. Remove crapi related docker volumes using `docker volume rm` command, probably will be named like this, use `docker volume ls` to find them
```
docker_mongodb-data
docker_postgresql-data
```
3. Download the latest version of docker-compose.yml - since there were some changes to that recently

And then try running it once more?

**Comment by 5qu1n7** [comment]
We have success...I had to stop all docker containers and I removed them all from my system, then I also stopped all docker volumes and removed them as well.  Redownloaded CRAPI, and no errors.

curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/develop/deploy/docker/docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6209  100  6209    0     0   1125      0  0:00:05  0:00:05 --:--:--  1511
                                                                                                                                                                                            
┌──(root㉿kali)-[~/API_Lab]
└─# VERSION=develop docker-compose pull

Pulling postgresdb      ... done
Pulling mongodb         ... done
Pulling crapi-identity  ... done
Pulling crapi-community ... done
Pulling crapi-workshop  ... done
Pulling crapi-web       ... done
Pulling mailhog         ... done
                                                                                                                                                                                            
┌──(root㉿kali)-[~/API_Lab]
└─# VERSION=develop docker-compose -f docker-compose.yml --compatibility up -d
Creating network "api_lab_default" with the default driver
Creating volume "api_lab_mongodb-data" with default driver
Creating volume "api_lab_postgresql-data" with default driver
Creating mailhog    ... done
Creating mongodb    ... done
Creating postgresdb ... done
Creating crapi-identity ... done
Creating crapi-community ... done
Creating crapi-workshop  ... done
Creating crapi-web       ... done

**Comment by ghoss23** [comment]
that was not helpful

**Comment by VicHinga** [comment]
Hey, I had the same issue: where crapi-web had an error, though managed to use the "restart" command

──(kali㉿kali)-[~/Labs/crAPI]
└─$ sudo docker-compose start
Starting postgresdb      ... done
Starting mongodb         ... done
Starting crapi-identity  ... done
Starting crapi-community ... done
Starting crapi-workshop  ... done
Starting crapi-web       ... error
Starting mailhog         ... done
Starting api.crapi.io    ... done

ERROR: for crapi-web  Container "74f550385d99" is unhealthy.
                                                                                                                    
┌──(kali㉿kali)-[~/Labs/crAPI]
└─$ sudo docker-compose ps    
     Name                    Command                   State                      Ports               
------------------------------------------------------------------------------------------------------
api.crapi.io      /app/server                      Up (unhealthy)   443/tcp                           
crapi-community   /bin/sh -c /app/main             Up (healthy)                                       
crapi-identity    /entrypoint.sh                   Up (healthy)                                       
crapi-web         /bin/sh -c /etc/nginx/ngin ...   Exit 255         127.0.0.1:8888->80/tcp            
crapi-workshop    /bin/sh -c /app/runner.sh        Exit 0                                             
mailhog           MailHog                          Up (healthy)     1025/tcp, 127.0.0.1:8025->8025/tcp
mongodb           docker-entrypoint.sh mongod      Up (healthy)     27017/tcp                         
postgresdb        docker-entrypoint.sh postgres    Up (healthy)     5432/tcp                          
                                                                                                                    
┌──(kali㉿kali)-[~/Labs/crAPI]
└─$ 
                                                                                                                    
┌──(kali㉿kali)-[~/Labs/crAPI]
└─$ sudo docker-compose restart
Restarting crapi-web       ... done
Restarting crapi-workshop  ... done
Restarting crapi-community ... done
Restarting crapi-identity  ... done
Restarting mailhog         ... done
Restarting mongodb         ... done
Restarting postgresdb      ... done
Restarting api.crapi.io    ... done
