### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by psiinon** [OWASP/crAPI#168]
In the main readme it states `You can use prebuilt images generated by our CI workflow.`
Thats not actually true is it? It looks to me like the images still have to be built locally.
Publishing your images to Docker Hub would make it _much_ easier for people to use them.

We test ZAP against a set of vulnerable apps every day and publish the results: https://www.zaproxy.org/docs/scans/

If the crAPI docker image was available on docker hub then we would be able to add crAPI much more easily.
Without that our plan would be to build and publish the crAPI docker image to docker hub ourselves 😉

**Comment by mathew-jose** [comment]
@psiinon our images are published on dockerhub through our ci. Using the docker compose file, we can use these images to start the application. The image of the identity service for example can be found in this link [(identity-service)](https://hub.docker.com/r/crapi/crapi-identity)
