### ISSUE TITLE
Inacessible mechanic_api when using HTTPS

### ISSUE THREAD

**Issue by yesitsjnovak** [OWASP/crAPI#187]
**Describe the bug**
"Could not connect to mechanic api" message when opening a service request due to HTTPS

**To Reproduce**
Configure access to crapi via HTTPS. Signup and configure your vehicle.
Try creating a service request.
WebUI shows the error: "Could not connect to mechanic api."
Service request is not created.

Checking the POST request done when creating the service request, we have the following request body:

`{"mechanic_code":"TRAC_JHN","problem_details":"Hi John, I am opening this request to replace blinker fluid\n","vin":"3GWHK50SJRX079062","mechanic_api":"https://crapi.testlab.local/workshop/api/mechanic/receive_report","repeat_request_if_failed":false,"number_of_repeats":1}`

The response body:

`{"message":"Could not connect to mechanic api."}`

Even though accessing the endpoint manually (https://crapi.testlab.local/workshop/api/mechanic/receive_report) does indeed work, seems like the application is not able to access it.

Manually changing the URL to HTTP only instead of HTTPS apparently solves it:

![image](https://user-images.githubusercontent.com/107484727/231530478-ff3c8eab-6737-4ede-8c57-1fad54fe92e8.png)

![image](https://user-images.githubusercontent.com/107484727/231530641-91942c7c-5076-41b5-81c6-7370b3f44dd4.png)

**Expected behavior**
The application should be able to access the mechanic api endpoint, even when using HTTPS. 

**Runtime Environment**
crAPI running behind traefik.
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by piyushroshan** [comment]
Seems lie you have setup a domain crapi.testlab.local which may not be understood by internal services.

**Comment by piyushroshan** [comment]
This should be fixed now.
