### ISSUE TITLE
Can't uninstall crAPI completely

### ISSUE THREAD

**Issue by zerodayhacker** [OWASP/crAPI#230]
HI. I'd like to do a fresh install of crAPI (I installed it using the Docker method). I removed all containers and images related to crAPI, then reinstalled it from scratch. But when I rebuild the containers and launch the app, I still get the users and mailhog history I had on my previous install.
How can I remove everything from my system and start with a completely fresh install? Any specific config files I need to delete?Thanks!

**Comment by piyushroshan** [comment]
You need to delete the docker volumes.

**Comment by zerodayhacker** [comment]
Works great. Thanks!

**Comment by piyushroshan** [comment]
Another workaround is to use the `--volume` option with docker-compose down
`docker compose -f docker-compose-new.yml --compatibility down --volume`
