### ISSUE TITLE
can't able to run this application

### ISSUE THREAD

**Issue by comrade99** [OWASP/crAPI#24]
Successfully install crAPI on docker , but it's not running on localhost.
Any suggestion ??

**Comment by moti13590** [comment]
same problem

**Comment by moti13590** [comment]
Host crapi-workshop:8000 not yet available...

**Comment by moti13590** [comment]
Hi, can you send screenshot of the response from crAPI-workshop?

**Comment by piyushroshan** [comment]
What command did you use to run? And also OS version please

**Comment by piyushroshan** [comment]
You should also be able to use prebuilt images. Refer the docs for the same. Closing this since there is no further update
