### ISSUE TITLE
Possible bug with first run using docker

### ISSUE THREAD

**Issue by rGn0** [OWASP/crAPI#278]
Hi, i have the error below when i'm trying to running crapi on docker using kali:
curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml                                                 1 ⨯

sudo docker-compose pull

sudo docker-compose -f docker-compose.yml --compatibility up -d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7512  100  7512    0     0  15619      0 --:--:-- --:--:-- --:--:-- 15617
Pulling postgresdb                  ... done
Pulling mongodb                     ... done
Pulling mailhog                     ... done
Pulling crapi-identity              ... done
Pulling crapi-community             ... done
Pulling crapi-workshop              ... done
Pulling crapi-web                   ... done
Pulling api.mypremiumdealership.com ... done
mailhog is up-to-date
api.mypremiumdealership.com is up-to-date
Starting mongodb ... 
Starting mongodb ... done

ERROR: for crapi-identity  Container "f10d75dd6f85" is unhealthy.
ERROR: Encountered errors while bringing up the project.
I tried to run the develop version but the application still with same error. It's can be a local problem or a bug? I look for the issues and don't found nothing close to this. My docker-compose version is 1.27.0.
Tks

**Comment by piyushroshan** [comment]
Fixed in the latest develop branch.

**Comment by piyushroshan** [comment]
The default_jwks.json was not at the right location
