### ISSUE TITLE
I can't run it on Docker :(

### ISSUE THREAD

**Issue by cakinshin** [OWASP/crAPI#29]

**Comment by piyushroshan** [comment]
Could you please more information on the errors seen and os info.

**Comment by cakinshin** [comment]
hi 
I can't  make crapi-workshop to run , it exit with error code 127 
I can't understand what it needs 

![docker error](https://user-images.githubusercontent.com/16290175/164993343-9470b15b-cd69-4b35-9349-e5ac193ae969.png)
[error log.txt](https://github.com/OWASP/crAPI/files/8550389/error.log.txt)

**Comment by mathew-jose** [comment]
As you was building the images from a Windows machine, try changing the EoL sequence encoding from CRLF to LF for the file `crAPI\services\workshop\runner.sh` before starting the application. It should be possible using VS Code Editor.

**Comment by cakinshin** [comment]
hi 
I changed EOL but now I'm getting /bin/sh: /app/runner.sh: not found error in crapi-workshop when I try to run it

**Comment by mathew-jose** [comment]
Could you clone the repo once more? I have added some batch files and written commands specific to Windows machine in the README.

**Comment by PauloASilva** [comment]
Keep in mind that you can easily run crAPI inside a virtual machine regardless your Operating System as long as you have VirtualBox and Vagrant: https://github.com/OWASP/crAPI#vagrant ;)

**Comment by piyushroshan** [comment]
You should be also use prebuilt images. Closing this since there is no further update and multiple workaround.
