### ISSUE TITLE
unable to install on linux

### ISSUE THREAD

**Issue by govi123govi** [OWASP/crAPI#33]
when i run build.sh i get this error
sudo ./build-all.sh                                                                                                                                                                                        1 ⨯
+ set -e
+ dirname ./build-all.sh
+ cd .
+ find ../../services/ -name build-image*
+ scripts=../../services/identity/build-image.sh
../../services/web/build-image.sh
../../services/community/build-image.sh
../../services/workshop/build-image.sh
+ echo Executing ../../services/identity/build-image.sh
Executing ../../services/identity/build-image.sh
+ bash -x ../../services/identity/build-image.sh
+ set -x
++ dirname ../../services/identity/build-image.sh
+ cd ../../services/identity
+ docker build -t crapi-identity .
Sending build context to Docker daemon    341kB
Step 1/14 : FROM maven:3.6-jdk-11 AS javabuild
Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by PauloASilva** [comment]
Hi @govi123govi,
meanwhile, in order to start hacking, you can [consider deploying crAPI locally on a virtual machine using vagrant](https://github.com/OWASP/crAPI#vagrant): I've tested it just now based on the `develop` branch and it worked.

Cheers,
Paulo A. Silva

**Comment by piyushroshan** [comment]
You should  also be able to use prebuilt images. Refer the docs for the same. Closing this since there is no further update and multiple workaround.
