### ISSUE TITLE
Cant see past-orders

### ISSUE THREAD

**Issue by moti13590** [OWASP/crAPI#39]
when I tryin to see my past orders it pop up a failed message, it's part of the challenge?
![past-orders](https://user-images.githubusercontent.com/104391485/166644688-8cc5cf42-0092-4bf9-843d-465b597f341d.PNG)

**Comment by mathew-jose** [comment]
This is a bug caused by an assertion error when the database connection isn't set to UTC time. Removing `USE_TZ = True` in the `services/workshop/crapi_site/settings.py` file should resolve this error.

**Comment by piyushroshan** [comment]
We have pushed changes to fix this.
We have pre built images now that you can use. 
Could you try the following and let us know.

Checkout develop branch and pull the changes.
Run the following to use the develop build images.
```
VERSION=develop docker-compose -f deploy/docker/docker-compose.yml --compatibility up -d
```

**Comment by moti13590** [comment]
it works.thanks
