### ISSUE TITLE
OAS Specification 

### ISSUE THREAD

**Issue by ehog** [OWASP/crAPI#7]
Hello, would it be possible to please provide an OAS or Swagger specification for the APIs in _/crAPI/blob/develop/services/web/src/constants/APIConstant.js_?

This would help in deploying and managing the APIs in this project with an API gateway.

**Comment by hnataraj** [comment]
@ehog see here: https://github.com/levoai/demo-apps/blob/main/crAPI/api-specs/openapi.json

**Comment by PauloASilva** [comment]
Hi @hnataraj,
I had the chance to read your medium post ;)
Wouldn't you like to give back to the community, contributing with a PR to OWASP crAPI?

Cheers,
Paulo A. Silva

**Comment by hnataraj** [comment]
Sounds good.

Best regards,

Harish

**Comment by piyushroshan** [comment]
Done
