### ISSUE TITLE
com.crapi.CRAPIBootApplication is having an issue with com.zaxxer.hikari.pool.HikariPool--"org.postgresql.util.PSQLException: The connection attempt failed."

### ISSUE THREAD

**Issue by stop-a** [OWASP/crAPI#73]
**Describe the bug**
I cannot get crAPI to start up. The error message is:
```
ERROR: for crapi-community  Container "1b2afedad26d" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
I'm not an expert at docker, so I borrowed steps from another filed issue.

A look at what the last gasp of the container was...
``` bash
$ sudo docker ps -a | grep 1b2afedad26d
1b2afedad26d   crapi/crapi-identity:latest   "/bin/sh -c 'java -j…"   3 minutes ago   Exited (1) 2 minutes ago                                              crapi-identity
```
The log file, a result of ```docker log 1b2afedad26d```
[docker_log_1b2afedad26d.txt](https://github.com/OWASP/crAPI/files/8838253/docker_log_1b2afedad26d.txt)

**To Reproduce**
I executed the following commands:
``` bash
$ curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml
$ sudo docker-compose pull
$ docker-compose -f docker-compose.yml --compatibility up -d
```

**Expected behavior**

I'm following direction in _Hacking APIs__, by Corey Ball and the project's instructions.

I'm expecting a service to be running on port 8000, and others.

**Runtime Environment**

``` bash
$ docker -v Docker version 20.10.14, build a224086349
$ uname -a
Linux infra 5.13.0-44-generic #49-Ubuntu SMP Wed May 18 13:28:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Please let me know if there's additional information you need.

**Comment by piyushroshan** [comment]
Looks like your postgres db did not come up. Could you provide logs for that.

**Comment by stop-a** [comment]
Certainly!

```
$ sudo docker logs d65b6fec4169 

PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-06-04 16:13:47.501 UTC [1] LOG:  starting PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-06-04 16:13:47.501 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-06-04 16:13:47.502 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-06-04 16:13:47.523 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-06-04 16:13:47.547 UTC [25] LOG:  database system was shut down at 2022-06-04 16:10:22 UTC
2022-06-04 16:13:47.565 UTC [1] LOG:  database system is ready to accept connections
2022-06-04 16:14:02.720 UTC [40] FATAL:  role "root" does not exist
```
The last message repeated a bunch, so I truncated.

**Comment by piyushroshan** [comment]
Ummm! This looks good. Could be just a startup timing issue.
Could you retry with
```
docker-compose -f docker-compose.yml --compatibility down
docker-compose -f docker-compose.yml --compatibility up -d
```
If not resolved, happy to jump on a session with you to debug it out.

**Comment by stop-a** [comment]
Heading out to dinner soon, so I won't be able to a session until tomorrow.

I pulled down docker-compose.yml again and retried, but got the same result. I don't see a change to docker-compose.yml.

Going through docker-compose.yml it looks like all the images have been the same for a while, so not sure what's changed.

I decided to play the one-of-these-things-is-not-like-the-others game to see if I could pinpoint a change that may have broken things.

I edited docker-compose.yml to pull the latest postgresql image instead of 14 and re-ran docker-compose. No change.
I undid the edit and changed all the crapi-* images to pull v1 instead of latest and re-ran docker-compose. No change.

Since the message is couldn't connect, I hopped inside the postgresql running image and it looks like Postgres is running:
``` bash
root@e1fddd97cd7a:/proc/net# grep postgres *
grep: dev_snmp6: Is a directory
grep: netfilter: Is a directory
grep: stat: Is a directory
unix:0000000000000000: 00000002 00000000 00010000 0001 01 10243282 /var/run/postgresql/.s.PGSQL.5432
grep: vlan: Is a directory
grep: xt_recent: Is a directory
root@e1fddd97cd7a:/proc/net# ls /var/run/postgresql
root@e1fddd97cd7a:/proc/net# ls -al /var/run/postgresql/
total 16
drwxrwsr-x 1 postgres postgres 4096 Jun  4 21:57 .
drwxr-xr-x 1 root     root     4096 May 28 11:51 ..
srwxrwxrwx 1 postgres postgres    0 Jun  4 21:57 .s.PGSQL.5432
-rw------- 1 postgres postgres   63 Jun  4 21:57 .s.PGSQL.5432.lock
root@e1fddd97cd7a:/proc/net# 
```

Maybe something changed in Spring that doesn't like connecting to Postgres anymore?

**Comment by stop-a** [comment]
What a revolting twist...

Installed Docker Desktop on my Mac. It's running at 12.10.16 of docker.

Go back to dev machine. Pull of Ubuntu's docker--which is at 12.10.14--and install Docker's docker (huh?) per this set of instructions: https://docs.docker.com/engine/install/ubuntu/

Now at 12.10.16 on the dev Ubuntu machine. Change docker-config to 'docker config' and now it works.

LOL. Docker's better?
