### ISSUE TITLE
Crapi-web not starting

### ISSUE THREAD

**Issue by Beoas** [OWASP/crAPI#76]
port 8888 isn't listening when I tried netstat -antp  but port 8025 is listening i.e I can localhost:8025 for mailhog is working on my web browser but localhost:8888 is not working... I tried to uncomment everywhere I saw ports in the yaml file but it as to be commented before it can run it's docker container.  After checking the state using docker inspect crapi-web, the result states that it is in an unhealthy state. I can't open the logs folder /var/lib/docker...

**Comment by Ph4t3** [comment]
Are all other containers healthy? See if you can get the logs by using the command
```docker logs crapi-web```

**Comment by Beoas** [comment]
Its not working.
" I'm getting illegal instruction (core dumped) " as my output

**Comment by mathew-jose** [comment]
Could you upload the log file of the identity container to understand which instruction causes this issue.

**Comment by nikhil-rajesh** [comment]
Closing as issue is stale and bug could not be reroduced.
Please reopen if issue persists.
