### ISSUE TITLE
ERROR: Invalid interpolation format for "crapi-identity" option in service "services": "crapi/crapi-identity:${VERSION:-latest}"

### ISSUE THREAD

**Issue by re4sonzy** [OWASP/crAPI#77]
ERROR: Invalid interpolation format for "crapi-identity" option in service "services": "crapi/crapi-identity:${VERSION:-latest}"
```
curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml

docker-compose pull

docker-compose -f docker-compose.yml --compatibility up -d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6013  100  6013    0     0   6919      0 --:--:-- --:--:-- --:--:--  6911
/home/hunter/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
ERROR: Invalid interpolation format for "crapi-identity" option in service "services": "crapi/crapi-identity:${VERSION:-latest}"
/home/hunter/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
ERROR: Invalid interpolation format for "crapi-identity" option in service "services": "crapi/crapi-identity:${VERSION:-latest}"
```

**Comment by piyushroshan** [comment]
Could you provide you os and shell info?

**Comment by piyushroshan** [comment]
To simply unblock you please replace the `${VERSION:-latest}` with `latest`

**Comment by re4sonzy** [comment]
> 

Hello, my os is Parrot Sec, shell is the default MATE terminator

**Comment by csestrada** [comment]
OS: Kali, Shell: Terminology 

Replacing the version with latest led to a port error on a similar line.

**Comment by Acheson7** [comment]
The docker compose is still having issues, it looks like another person (possibly a teacher) found a solution. the video is the following https://www.youtube.com/watch?v=ByW_yobA2aM. 
Is there a way to have it not rely on Ubuntu 18 as the base operating system for docker?

**Comment by MarkMorow** [comment]
Same issue. 
OS: Ubuntu 20.04.4 LTS
Shell: 5.15.0-41-generic

**Comment by piyushroshan** [comment]
Its a docker compose issue. It can be fixed by upgrading docker-compose to latest. As I fix I will add docker compose compatibility version.

**Comment by MarkMorow** [comment]
I was on the latest version from the package manager, 1.25.0. After removing it and pulling directly from docker I was then on v2.8.0. crAPI did then start as expected. For anyone else running into this I used the following commands. 

sudo apt-get remove docker-compose

VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')

DESTINATION=/usr/local/bin/docker-compose

sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION

sudo chmod 755 $DESTINATION

This was taken from https://stackoverflow.com/questions/49839028/how-to-upgrade-docker-compose-to-latest-version

**Comment by janibashamd** [comment]
Faced same issue and able to pull repo with above resolution steps.
Note: Even after above steps if docker-compose -v is not giving you output, then you have to copy docker-compose binary from /usr/local/bin /usr/bin/

**Comment by Sim4n6** [comment]
The problem arises from the fact that the repository version of docker-compose is old.

**Comment by dmdhrumilmistry** [comment]
> The problem arises from the fact that the repository version of docker-compose is old.

Might be, But even after upgrading to the latest version of docker referring [documentation](https://docs.docker.com/engine/install/debian/) it didn't work for me on Debian 11.

**Comment by Apollo9999** [comment]
Please Use link https://docs.docker.com/compose/install/  rather than link  https://stackoverflow.com/questions/49839028/how-to-upgrade-docker-compose-to-latest-version

**Comment by sanket-mundra** [comment]
Can you please assign it to me?
