### ISSUE TITLE
ERROR: An HTTP request took too long to complete, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

### ISSUE THREAD

**Issue by mrbiggleswirth** [OWASP/crAPI#83]
---
**1. Describe the bug**
== A clear and concise description of what the bug is ==
.
Running docker-compose command always crashes my Amazon AWS EC2 server!

- July 2022

- Amazon AWS EC2: Ubuntu 22.04 LTS

- crapi-identity container memory: 512M

```python
$ export COMPOSE_HTTP_TIMEOUT=120;

$ printenv | grep COM
COMPOSE_HTTP_TIMEOUT=120
```
.
Then starting **docker-compose** always crashes my Amazon AWS EC2 server. Also it still complains that my current COMPOSE_HTTP_TIMEOUT value is 60 seconds even though I have set it to 120 seconds.
```python
$ sudo docker-compose -f docker-compose.yml --compatibility up -d

Starting postgresdb ... done
Starting mongodb    ... done
Starting mailhog    ... done
Recreating crapi-identity ... done

# ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
# If you encounter this issue regularly because of slow network conditions,
# consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

--- Server ALWAYS crash here! ---
```
How do I properly set my COMPOSE_HTTP_TIMEOUT value. Do I need to run a certain command to update my export command, before running docker-compose?

---
**2. To Reproduce**
== Steps to reproduce the behavior. If applicable, add screenshots to help explain your problem. ==

```python
# Amazon AWS EC2: Ubuntu 22.04 LTS

$ sudo ufw status
Status: inactive

$ curl -o docker-compose.yml https://raw.githubusercontent.com/OWASP/crAPI/main/deploy/docker/docker-compose.yml

$ sudo docker-compose pull

# Quote from a different ticket:
"Issue fixed by increasing the memory for the 'crapi-identity' block in 'docker-compose.yml' to be 512M, from 256M."

$ nano docker-compose.yml

$ export COMPOSE_HTTP_TIMEOUT=120;

$ printenv | grep COMPOSE
COMPOSE_HTTP_TIMEOUT=120
```
.
```python
$ sudo docker-compose -f docker-compose.yml --compatibility up -d

Starting postgresdb ... done
Starting mongodb    ... done
Starting mailhog    ... done
Recreating crapi-identity ... done

# ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
# If you encounter this issue regularly because of slow network conditions,
# consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

---
**3. Expected behavior**
== A clear and concise description of what you expected to happen. ==
.
I'm expecting the COMPOSE_HTTP_TIMEOUT value to be 120 seconds in the ERROR message before the Amazon AWS EC2 server crashes.
```python
# ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
# If you encounter this issue regularly because of slow network conditions,
# consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

---
**4. Runtime Environment**
== Sytem/Environemnt information (e.g Output of <b>docker -v</b> and <b>uname -a</b>) ==

```python
$ docker -v
Docker version 20.10.17, build 100c701

$ uname -a
Linux ip-xxx-xx-xx-xxx 5.15.0-1015-aws
#19-Ubuntu SMP Wed Jun 22 17:44:56 UTC 2022
x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mrbiggleswirth** [comment]
@piyushroshan Hi, these are my Amazon AWS EC2 specs:

```python
# Amazon Machine Image (AMI):
Ubuntu Server 22.04 LTS (HVM), SSD Volume Type - "Free tier eligible"

# Architecture:
64-bit (x86)

# Instance type:
t3.micro - "Free tier eligible"

# Configure storage:
1x 8 GiB, gp2 Root Volume
```
.
```python
# Custom inbound rules besides the default HTTP, HTTPS and SSH ports.

      "Type": Custom TCP
"Port range": 3000
    "Source": Anywhere-IPv4
```

**Comment by piyushroshan** [comment]
Thanks for the info. Let me try this out with your configs.

**Comment by mrbiggleswirth** [comment]
@piyushroshan I meant `t2.micro` not `t3.micro`. I have Amazon server containers created in two different regions. It always confuses me which one I'm working on.

```python
# Instance type:
t2.micro - "Free tier eligible"
```

**Comment by AHarmlessPyro** [comment]
I've tried running this on a fresh `t2.micro` running `ubuntu 22.04`. 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/32181677/194754159-df379a82-17e4-4391-a961-e54ee7324167.png">

It builds fine for me. 

It seems that the root cause should be related to slow fetch speeds as mentioned by docker, but imo on the aws ec2 machine fetch speeds are fast enough that http timeouts (especially of 60s) shouldn't be the issue unless some weird proxy is involved somewhere that's slowing downloads down significantly. 

Looking around on [docker compose git](https://github.com/docker/compose/issues/3633), for most users, restarting docker helps, while for others it seems like a machine resource limit which is understandable for this given that we're running about 7 services on a rather tiny machine. 

I know this isn't a great response, but it seems like the underlying issue is more of a session/machine resources issue. 

Also, sidenote : docker `COMPOSE_HTTP_TIMEOUT` is deprecated env var, since about 2017 (docker v1.10.0) or so, so maybe it has been phased out completely and the error just hasn't been updated.

**Comment by AHarmlessPyro** [comment]
@JBAhire I haven't included this in the `hacktober` gform as it's not really a solution to the problem and (atleast for me) I haven't been able to recreate this locally or on a remote machine. Even a `HTTP_COMPOSE_TIMEOUT=1` (which should timeout after 1s, which should cause it to fail every time doesn't seem to be honored. This further reinforces the idea that the env var isn't honored by docker anymore and is just kept there as legacy code that should've been removed by hasn't. In these cases it's triggered by some other phenomenon that just happens to trigger the same error.

**Comment by nikhil-rajesh** [comment]
Closing as issue is stale and does not seem to be a crapi bug. 
Please feel free to reopen if issue persists.
