### ISSUE TITLE
How do you stop crAPI web app from running on server?

### ISSUE THREAD

**Issue by mrbiggleswirth** [OWASP/crAPI#84]
This is not a bug or a feature request. But I'm just wondering how do you stop the crAPI web app from running on the server?

```python
# Start crAPI web app!
$ sudo docker-compose -f docker-compose.yml --compatibility up -d

# Stop crAPI web app?
???
```

**Comment by piyushroshan** [comment]
`docker-compose -f docker-compose.yml --compatibility down` from the dir `up` was run.

**Comment by mrbiggleswirth** [comment]
@piyushroshan Thanks, it worked!
