### ISSUE TITLE
Application not accessible from EC2

### ISSUE THREAD

**Issue by janibashamd** [OWASP/crAPI#94]
**Describe the bug**
Application is available from the machine but not from internet.

**To Reproduce**
1. Deploy EC2 instance with docker-compose
2. Check the Ec2 security group and open 8888 to access from outside
3. Follow steps provided in readme to install application
4. Try to access application using http::<ec2-publicip>:8888

**Expected behavior**
Application should be available from outside world but observed crAPI-web is mapped to 127.0.0.1 instead of 0.0.0.0 causing this issue.

**Runtime Environment**
Docker-compose: v2.9.0

**Comment by janibashamd** [comment]
I updated ports section to 0.0.0.0 in docker-compose after which application is accessible.

**Comment by zerodayhacker** [comment]
Hi janibashamd,
I'm running into the same problem. I'm new to docker-compose (and docker…). Can you give details on how you updated the ports section to 0.0.0.0?
Step by step would be greatly appreciated. 👋

**Comment by zerodayhacker** [comment]
Hi janibashamd,
OK, never mind, I found out how to do it. 🙂👍
For anyone else wanting some help with this:
With a file editor, open the `docker-compose.yml` file which should be in your home directory (you may want to do a backup copy of the file first).
Go down to the `crapi-web:` section and under `ports:` change the following line: 
`- "127.0.0.1:8888:80"`
into
`- "0.0.0.0:8888:80"`
Then save and quit.
Then run the following command:
`sudo docker-compose -f docker-compose.yml --compatibility up -d`
This rebuilds the `crapi-web` container.
Now the app should be accessible from other hosts on your network.
